name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --workspace --all-targets
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Test
        run: cargo test --workspace --all-targets

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-llvm-cov
        run: |
          curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-installer.sh | sh
      - name: Run coverage (workspace)
        run: |
          cargo llvm-cov --workspace --lcov --output-path lcov.info
          cargo llvm-cov --workspace --reporter text > coverage.txt
      - name: Run coverage (per-crate)
        run: |
          cargo llvm-cov -p gh-otco-api --reporter text > coverage.gh-otco-api.txt
          cargo llvm-cov -p gh-otco-cli --reporter text > coverage.gh-otco-cli.txt
          cargo llvm-cov -p gh-otco-api --lcov --output-path lcov.gh-otco-api.info
          cargo llvm-cov -p gh-otco-cli --lcov --output-path lcov.gh-otco-cli.info
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            lcov.info
            coverage.txt
            coverage.gh-otco-api.txt
            coverage.gh-otco-cli.txt
            lcov.gh-otco-api.info
            lcov.gh-otco-cli.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: |
            lcov.info
            lcov.gh-otco-api.info
            lcov.gh-otco-cli.info
          flags: total,api,cli
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Print coverage summary
        run: |
          echo "=== Coverage Summary (text) ==="
          cat coverage.txt
